name: ci & build-push

on:
  push:
    branches:
      - 'master'

jobs:
  ci-build-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      -
        name: Set up golangci-lint
        run: GOBIN=$(go env GOPATH)/bin make golangci-lint
      -
        name: Lint + build + test
        run: make all
      -
        name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: charlessortlist/k8s-service-broadcasting:latest
